language: ruby
cache: bundler
sudo: false
addons:
  postgresql: '9.6'
rvm:
  - 2.5.1
before_install:
  - gem update --system
before_script:
  - bundle exec rake app:db:test:prepare RAILS_ENV=test
script:
  - bundle exec rspec spec
